-- MySQL Script generated by MySQL Workbench
-- Tue Aug 13 00:04:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema g6Mj2lugZA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `g6Mj2lugZA` ;

-- -----------------------------------------------------
-- Schema g6Mj2lugZA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `g6Mj2lugZA` DEFAULT CHARACTER SET utf8 ;
USE `g6Mj2lugZA` ;

-- -----------------------------------------------------
-- Table `g6Mj2lugZA`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g6Mj2lugZA`.`users` ;

CREATE TABLE IF NOT EXISTS `g6Mj2lugZA`.`users` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(16) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `college_ID` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `g6Mj2lugZA`.`initiatives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g6Mj2lugZA`.`initiatives` ;

CREATE TABLE IF NOT EXISTS `g6Mj2lugZA`.`initiatives` (
  `initiative_id` INT NOT NULL,
  `initiative_name` VARCHAR(45) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `strategy_id` INT NOT NULL,
  `college_id` INT NOT NULL,
  `initiative_active` VARCHAR(45) NOT NULL,
  `initiative_progress_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`initiative_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g6Mj2lugZA`.`colleges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g6Mj2lugZA`.`colleges` ;

CREATE TABLE IF NOT EXISTS `g6Mj2lugZA`.`colleges` (
  `college_id` INT NOT NULL,
  `college_short_name` VARCHAR(45) NOT NULL,
  `college_long_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`college_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g6Mj2lugZA`.`milestones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g6Mj2lugZA`.`milestones` ;

CREATE TABLE IF NOT EXISTS `g6Mj2lugZA`.`milestones` (
  `milestone_id` INT NOT NULL,
  `milestone_description` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `initiative_id` VARCHAR(45) NOT NULL,
  `milestone_active` VARCHAR(45) NOT NULL,
  `milestone_progress_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`milestone_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g6Mj2lugZA`.`strategy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g6Mj2lugZA`.`strategy` ;

CREATE TABLE IF NOT EXISTS `g6Mj2lugZA`.`strategy` (
  `strategy_id` INT NOT NULL,
  `strategy_name` VARCHAR(45) NOT NULL,
  `strategy_description` VARCHAR(255) NOT NULL,
  `college_id` VARCHAR(45) NOT NULL,
  `active_strategy` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`strategy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g6Mj2lugZA`.`tracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g6Mj2lugZA`.`tracking` ;

CREATE TABLE IF NOT EXISTS `g6Mj2lugZA`.`tracking` (
  `strategy_id` INT NOT NULL,
  `initiative_id` INT NOT NULL,
  `college_id` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
